site_name: Dunstwolke
site_url: https://dunstwolke.org/
repo_url: https://github.com/Dunstwolke/core
edit_uri: null
docs_dir: src

nav:
  - Home: index.md
  - Dunstblick:
    - 'About': dunstblick.md
    - 'Layout Engine': dunstblick/layout-engine.md
    - 'Layout Language': dunstblick/layout-language.md
    - 'Protocol': dunstblick/protocol.md
    - 'Data Types': dunstblick/types.md
    - 'Widgets': dunstblick/widgets.md
  - Dunstnetz: dunstnetz.md
  - DunstFS: dunstfs.md
theme:
    name: mkdocs
    nav_style: light